// BUS events
const __ON_RESTART_LEVEL = '__ON_RESTART_LEVEL';
const __ON_CHANGE_LEVEL = '__ON_CHANGE_LEVEL';
const __ON_LEVEL_OPENED = '__ON_LEVEL_OPENED';
const __ON_LEVEL_CLOSED = '__ON_LEVEL_CLOSED';

const __ON_SHOOT = '__ON_SHOOT'
const __ON_ADD_SCORE = '__ON_ADD_SCORE';
const __ON_THROWS_COUNT_UPDATED = '__ON_THROWS_COUNT_UPDATED';
const __ON_SCORE_VALUE_UPDATED = '__ON_SCORE_VALUE_UPDATED';
const __ON_LANGUAGE_CHANGED = '__ON_LANGUAGE_CHANGED';
const __ON_SHOW_SETTINGS_WINDOW = '__ON_SHOW_SETTINGS_WINDOW';
const __ON_SHOW_WIN_WINDOW = '__ON_SHOW_WIN_WINDOW';

// Levels
const LEVEL_NAME_SEPARATOR = '_';
const LEVEL_1 = `level${LEVEL_NAME_SEPARATOR}1`;
const LEVEL_2 = `level${LEVEL_NAME_SEPARATOR}2`;
const LEVEL_3 = `level${LEVEL_NAME_SEPARATOR}3`;
const ALL_LEVELS = [LEVEL_1, LEVEL_2, LEVEL_3];

// Windows
const WIN_WINDOW = 'win';
const SETTINGS_WINDOW = 'settings';

// Config
const ACTIVE_BUTTON_OPACITY = 1;
const NOT_ACTIVE_BUTTON_OPACITY = 0.5;
const CLOUDS_TIME = 60;
const BIG_BLOCK_HP = 100;
const BREAK_BLOCK_HP = 50;
const BIG_BLOCK_SCORE_VALUE = 50;
const BREAK_BLOCK_SCORE_MAP = new Map([
    ['break_1', 10],
    ['break_2', 10],
    ['break_3', 10],
    ['break_4', 10],
    ['break_5', 5],
    ['break_6', 0],
    ['break_7', 0],
    ['break_8', 0],
    ['break_9', 10],
]);
const BREAK_STEP = 50;
const RATING_FOR_TWO_STARS = 0.55;
const RATING_FOR_THREE_STARS = 0.85;
const SCORE_WEIGHT_RATING = 0.35;
const THROW_WEIGHT_RATING = 0.65;
const PROJECTILE_SIZE = 28;
const PROJECTILE_LOADED_DEFAULT_Z = -4;
const PROJECTILE_LOADED_Z = -2;
const PROJECTILE_FLYING_Z = -20;
const PROJECTILE_SHOW_TRAIL_DELAY = 0.05;
const PROJECTILE_LIFETIME = 2;
const PREDICTION_PATH_DOTS_COUNT = 22;
const PREDICTION_PATH_DOT_SIZE_MIN = 4;
const PREDICTION_PATH_DOT_SIZE_MAX = 9;
const PREDICTION_PATH_DOT_ALPHA_MIN = 0.78;
const PREDICTION_PATH_DOT_ALPHA_MAX = 0.96;
const PREDICTION_PATH_STEPS_PER_DOT = 1;
const PREDICTION_PATH_GRAVITY_PER_STEP = 0.28;
const SLINGSHOT_RUBBER_CONTACT_RADIUS = PROJECTILE_SIZE * 0.38;
const SLINGSHOT_MIN_SHOT_PULL = 30;
const SLINGSHOT_MAX_POWER_PULL = 190;
const SLINGSHOT_SHOT_POWER = 0.2;
const SLINGSHOT_VISUAL_PULL_SCALE = 0.62;
const SLINGSHOT_MAX_VISUAL_PULL = 80;
const SLINGSHOT_RELOAD_DELAY = 0.45;
const SLINGSHOT_POWER_PULL_Y_CONSTRAINT = 85;
// Local storage
const LS_SOUND_DISABLED_VALUE = 'sound';